---
title: "Citibike ain't got Flow"
author: "Will Bartlett"
date: "July 17, 2016"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
setwd("/Users/williambartlett/Downloads")
citibike_df = read.csv("201606-citibike-tripdata.csv")
library(ggplot2)
library(ggmap)
library(dplyr)
library(maps)
library(mapdata)
library(rgdal)

my_citibike_df = select(citibike_df,
                        starttime, 
                        start.station.name, 
                        start.station.latitude,
                        start.station.longitude,
                        end.station.name,
                        stoptime)
my_citibike_df$starttime = as.character(my_citibike_df$starttime)
my_citibike_df$starttime = strptime(my_citibike_df$starttime, "%m/%d/%Y %H:%M")
my_citibike_df = my_citibike_df %>% 
      mutate(day_of_week_start = weekdays(my_citibike_df$starttime)) %>%
      mutate(hour_start = my_citibike_df$starttime$hour)

my_citibike_df$stoptime = as.character(my_citibike_df$stoptime)
my_citibike_df$stoptime = strptime(my_citibike_df$stoptime, "%m/%d/%Y %H:%M")
my_citibike_df = my_citibike_df %>% 
      mutate(day_of_week_end = weekdays(my_citibike_df$stoptime)) %>%
      mutate(hour_end = my_citibike_df$stoptime$hour)

day_start = my_citibike_df$day_of_week_start
weekday_log_start = ifelse(day_start == "Monday" |
                           day_start == "Tuesday" |
                           day_start == "Wednesday" |
                           day_start == "Thursday" |
                           day_start == "Friday", T, F)
day_end = my_citibike_df$day_of_week_end
weekday_log_end = ifelse(day_end == "Monday" |
                           day_end == "Tuesday" |
                           day_end == "Wednesday" |
                           day_end == "Thursday" |
                           day_end == "Friday", T, F) 
my_citibike_df = mutate(my_citibike_df, weekday_logical_start = weekday_log_start)
my_citibike_df = mutate(my_citibike_df, weekday_logical_end = weekday_log_end)
weekday_df_start = my_citibike_df[my_citibike_df$weekday_logical_start == T, c(-1,-6)]
weekend_df_start = my_citibike_df[my_citibike_df$weekday_logical_start == F, c(-1,-6)]

weekday_df_end = my_citibike_df[my_citibike_df$weekday_logical_end == T,c(-1,-6)]

#trip by hour map functions

maps_percent = function(x, y){
      library(ggplot2) 
      library(dplyr)
      library(maps)
      library(mapdata)
      library(rgdal)
      
      stat_lat_long = weekday_df_start[,c(1,2,3)]
      stat_lat_long = unique(stat_lat_long)
      
      nyc = get_map(location = "New York City", maptype = "roadmap", zoom = 12)
      nycMap = ggmap(nyc)
      nobs = filter(weekday_df_start, hour_start >= x & hour_start <= y)
      nobs = nrow(nobs)
      weekday_df_x_y = filter(weekday_df_start, hour_start >= x & hour_start <= y) %>%
            group_by(start.station.name) %>%
            summarise(trips = 100*(n()/nobs)) %>%
            inner_join(stat_lat_long, by = "start.station.name")
      max_station = arrange(weekday_df_x_y, desc(trips))
      print(max_station[1:5,])
      med = median(max_station$trips)
      print(med)
      hour_usage_map = nycMap + geom_point(data = weekday_df_x_y, 
                                           mapping = aes(x =start.station.longitude, 
                                                         y = start.station.latitude,
                                                         color = trips,
                                                         size = trips)) +
            coord_map(xlim = c(-74.03, -73.95), ylim = c(40.68, 40.79)) +
            scale_color_gradient(low = "yellow", high = "black") +
            ggtitle(paste0("% of all Citibike Trips Started at each Dock for Hours ", x, ":00 through ", y, ":00"))
      return(hour_usage_map)
}

maps_ratio = function(x, y){
      library(ggplot2) 
      library(dplyr)
      library(maps)
      library(mapdata)
      library(rgdal)
      
      stat_lat_long = weekday_df_start[,c(1,2,3)]
      stat_lat_long = unique(stat_lat_long)
      
      end.station.number = filter(weekday_df_end, hour_end >= x & hour_end <= y) %>%
            group_by(end.station.name) %>%
            summarise(end_trips = n())
      
      nyc = get_map(location = "New York City", maptype = "roadmap", zoom = 12)
      nycMap = ggmap(nyc)
      weekday_df_x_y = filter(weekday_df_start, hour_start >= x & hour_start <= y) %>%
            group_by(start.station.name) %>%
            summarise(start_trips = n()) %>%
            inner_join(end.station.number, by = c("start.station.name" = "end.station.name")) %>%
            inner_join(stat_lat_long, by = "start.station.name")%>%
            mutate(trips_ratio = start_trips/end_trips)
      max_station = arrange(weekday_df_x_y, desc(trips_ratio))
      print(max_station[1:5, c(1,6,2,3)])
      med = median(max_station$trips_ratio)
      print(med)
      hour_usage_map = nycMap + geom_point(data = weekday_df_x_y, 
                                          mapping = aes(x =start.station.longitude, 
                                                         y = start.station.latitude,
                                                         color = trips_ratio,
                                                         size = trips_ratio)) +
            coord_map(xlim = c(-74.03, -73.95), ylim = c(40.68, 40.79)) +
            scale_color_gradient(low = "yellow", high = "black") +
            ggtitle(paste0("Ratio of Citibike Trips Started:Ended at each Dock for Hours ", x, ":00 through ", y, ":00"))
      return(hour_usage_map)
}

```



###Citibike Usage Throughout the Day; (Trip Starts by Hour) 
```{r }
g_allday_hour = ggplot(my_citibike_df, mapping = aes(hour_start))
g_weekday_hour = ggplot(weekday_df_start, mapping = aes(hour_start))
g_weekend_hour = ggplot(weekend_df_start, mapping = aes(hour_start))

g_allday_hour + geom_bar() + 
      xlab("Hour of the Day") + 
      ylab("Number of Trips Started") +
      ggtitle("Number of Citibike Trips Started Each Hour")

g_weekday_hour + geom_bar() + 
      xlab("Hour of the Day") + 
      ylab("Number of Trips Started") +
      ggtitle("Number of Citibike Trips Started Each Hour (WEEKDAYS)")

g_weekend_hour + geom_bar() + 
      xlab("Hour of the Day") + 
      ylab("Number of Trips Started") +
      ggtitle("Number of Citibike Trips Started Each Hour (WEEKENDS)")
```

### Citibike Usage and Station Flow by Dock
```{r warning = FALSE}
#General Usage
maps_percent(0,23)

maps_ratio(0, 23)
```

### Citibike Station Flow by Dock, Hours 6-10
```{r warning = FALSE}
maps_ratio(6, 10)
maps_ratio(11, 15)
maps_ratio(16, 20)

```



